title: Reservations
modelClass: DigitalArtisan\Studio\Models\Reservation
list: $/digitalartisan/studio/models/reservation/columns.yaml
recordUrl: 'digitalartisan/studio/reservations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: start
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
